### ISSUE TITLE
Vanished After PF2 Update

### ISSUE THREAD

**Issue by josh-koonce** [oWave/pf2e-flatcheck-helper#1]
Howdy. First off, love this mod. Full automation kind of takes away from the flat check experience, so this mod is perfect.

I think I may have just upgraded my PF2 system a little further than the mod is ready for, but since updating I no longer see PF2 Flat Check Helper in the modules list and it's not in my chat window.

So this is probably a "wait for the update and it'll work again" situation, but I'm finding myself a little lost in the Foundry modules and systems updates world lol.

**Comment by oWave** [comment]
I'm running the latest foundry and pf2e system version, and it's working fine. There's no maximum core/system version in the manifest, so it really should not disappear after an update.

**Comment by josh-koonce** [comment]
Okay, it's probably a conflict with another mod that updated then. I'll isolate and find it! Thank you!

**Comment by josh-koonce** [comment]
Just a follow up in case anyone else runs into the issue. 1. The name change threw me off, I wasn't finding the mod because I was looking for the wrong name LOL. and 2. I had to uncheck the "Show Flat Check buttons" option and reload, then check it again to make it reappear. Works fine now.

**Comment by oWave** [comment]
No idea how I didn't spot this while testing, but the "Enable flat check buttons" now works correctly.

**Comment by josh-koonce** [comment]
Lol ain’t coding fun. And thanks!

**Comment by josh-koonce** [comment]
Whoops

**Comment by josh-koonce** [comment]
Whoops
