### ISSUE TITLE
Request: Add optional messages to chat for both Delay and Return button actions

### ISSUE THREAD

**Issue by fraserstanton** [oWave/pf2e-flatcheck-helper#10]
I use a different encounter tracker (Mini Tracker), so I don't see the Return to combat button unless I open up the built in encounter tracker.
Just wondering if you can have a button show up (additionally) on the right click token menu in the same place as the delay button when appropriate (i.e. if Delayed and not your turn and you are not naturally next anyway).
Perhaps an optional chat message when the character does delay? Just so it is more obvious what the PC is doing that turn. Same for Return.

**Comment by oWave** [comment]
There should be a return button in the token HUD
![image](https://github.com/oWave/pf2e-flatcheck-helper/assets/9253349/e027385b-d9b8-4afc-bc4b-592d3a266230)

The allow return settings and socketlib need to be enabled for that to show up

Delay/Return message is an idea I can look at later. Until then, you could just have your players use the delay action so you have something in chat.

**Comment by fraserstanton** [comment]
Weird, first time I tested it (socketlib enabled), I didn't see the button, but tested it now and it works. Maybe I was testing with only 2 people in initiative and it doesn't show up if your turn is naturally next.
I will change title for optional message. Thanks, nice work.

**Comment by oWave** [comment]
Added as a setting (enabled by default) in v0.9
