### ISSUE TITLE
Spirit Link - is activation immediately after casting the spell possible?

### ISSUE THREAD

**Issue by carfesh** [oWave/pf2e-flatcheck-helper#12]
Thank you for the work you have put into this module; I found a small issue regarding the spirit link activation that I wanted to raise here. The spell's description says that the link occurs "When you Cast this Spell and at the start of each of your turns".

The way you have described it and which seems to be implemented right now is that the effect happens only at the beginning of subsequent turns.

Do you see a way to be able to achieve the same effect the moment the spell is cast?

**Comment by oWave** [comment]
Added in 0.7.4. I totally haven't been forgetting that it also transfer on cast this entire time.

**Comment by carfesh** [comment]
Awesome, thank you so much!
