### ISSUE TITLE
V12 update

### ISSUE THREAD

**Issue by belkasro** [oWave/pf2e-flatcheck-helper#14]
this still being worked on or no longer worked on?

**Comment by oWave** [comment]
Soon™
Been busy, if you're feeling adventurous you can remove the maximum from the module manifest. I did give delaying a quick test and nothing seemed broken, but wanted to test everything before I push an update

**Comment by oWave** [comment]
https://github.com/oWave/pf2e-flatcheck-helper/releases/tag/0.8.0
