### ISSUE TITLE
Players unable to Return from Delay with the appropriate button

### ISSUE THREAD

**Issue by Aeristoka** [oWave/pf2e-flatcheck-helper#15]
FoundryVTT: 12.328
PF2e: 6.0.4

Players used to be able to return themselves to initiative by clicking the spinning Clock icon, now I (as GM) have to return them whenever they'd like to re-join initiative.

No errors on the console for Player or GM when the player is spam-clicking the clock to return.

**Comment by oWave** [comment]
Fixed in 0.8.1

**Comment by Aeristoka** [comment]
> Fixed in 0.8.1

Excellent! Verified as working just now.
