### ISSUE TITLE
Delay seems to ignore a player's turn

### ISSUE THREAD

**Issue by 117Dios** [oWave/pf2e-flatcheck-helper#18]
Hi. I've noticed that just after the beginning of an encounter, if the 1st creature to go decides to delay, the 2nd creature's turn will be skipped. There seems to be no problems if the delay is done later at any point.

Here Gnakk is 1st and decides to go after Sheeva
![1](https://github.com/user-attachments/assets/5e4fad8a-176f-4c6a-be48-26b6b02cf906)

Here is immediately after he confirms
![image](https://github.com/user-attachments/assets/52d81969-e1e0-475d-9eeb-d734f7fad35a)

**Comment by oWave** [comment]
Can reproduce. What a fascinating issue.
Just to confirm: You're using the "Prompt for new initiative" setting? Because it doesn't appear to happen without it, and that at least gives me somewhere to start debugging.

**Comment by 117Dios** [comment]
Yes, that setting is checked. Unchecking it doesn't cause any issue to me either

**Comment by oWave** [comment]
Not proud of this fix (it's just a 50ms wait between ending the turn and updating initiative), but I'm calling this a foundry core bug because everything in my code should be awaited properly. 
Let me know if it still happens, and I might try to dive deeper into the foundry code.
