### ISSUE TITLE
[Feature] Support for Combat Carousel Tracker

### ISSUE THREAD

**Issue by cadowtin** [oWave/pf2e-flatcheck-helper#2]
It would be nice if the delay buttons had support for this module https://github.com/theripper93/combat-tracker-dock. I started on an implementation, however it gets overridden by the tracker module as libwrapper currently doesn't wrap the interaction

**Comment by oWave** [comment]
I just took a quick look and don't really see a way to add buttons to the dock. The combatant buttons seem to be hard-coded (https://github.com/theripper93/combat-tracker-dock/blob/fa512259752fc2206118816203140527eb98035b/templates/combatant-portrait.hbs#L39), same with the combat control buttons on the sides.

I'd rather not manually add buttons to the DOM for every single module the modifies the encounter tracker. What was your idea/implementation for this?

**Comment by 117ksk** [comment]
I came here to add my +1 to this feature request if its possible. The Combat Carousel Tracker module is the main combat tracker for V11 and would be very useful to have the utility button for delay included somehow. Thanks!

**Comment by oWave** [comment]
Moving this #6. I listed some ideas to solve this there as well.
