### ISSUE TITLE
Unable to install via manifest URL

### ISSUE THREAD

**Issue by apoapostolov** [oWave/pf2e-flatcheck-helper#3]
![image](https://github.com/oWave/pf2e-flatcheck-helper/assets/4083812/f6fe6cce-23e9-4fb5-a676-23280f1bd922)

**Comment by oWave** [comment]
What manifest URL did you try to use? The module.json link on the [releases page](https://github.com/oWave/pf2e-flatcheck-helper/releases) should work.

**Comment by apoapostolov** [comment]
It worked, thanks.
