### ISSUE TITLE
Feature request : Add support for Mini Tracker

### ISSUE THREAD

**Issue by uniwars** [oWave/pf2e-flatcheck-helper#5]
Hi, would that be possible to add support for Mini tracker module ?

https://github.com/reonZ/mini-tracker

https://user-images.githubusercontent.com/65986545/254717403-c28592e3-e539-4954-8269-4ad4cdf54dc2.png

I opened the same feature request for mini tracker as I don't know which need to implement the other.

**Comment by oWave** [comment]
This would most certainly need to be implemented on my side, but minitracker also changes the way ties are handled.
Half of making this work would be something that is needed for #2 as well, but handling decimal-ties is more math.

Going to track this under #6.
