### ISSUE TITLE
Error on More Flat Check button

### ISSUE THREAD

**Issue by ottyn** [oWave/pf2e-flatcheck-helper#8]
Foundry 11.308
PF2e System 5.4.2
PF2e Utility Buttons 0.5.3

When an actor is selected on the scene, if you click on the More Flat Checks button, you do not get the popup window and the following error shows in the console.  If no actor is selected, the dialog window opens correctly.

![error](https://github.com/oWave/pf2e-flatcheck-helper/assets/97130150/1a6ba93c-2199-4324-86ef-8932a2b1bb7f)

**Comment by oWave** [comment]
Fixed in 0.5.4. Missed that when fixing the other button.
