### ISSUE TITLE
Bug Report: Weird Formatting in Tracker on 5.5.0

### ISSUE THREAD

**Issue by GorgoPrimus** [oWave/pf2e-flatcheck-helper#9]
![Untitled](https://github.com/oWave/pf2e-flatcheck-helper/assets/126842722/33d3062e-e10d-4451-aa47-d38b9f7a2a1e)

Very minor new bug that makes the tracker taller than it should be prior to initiative being rolled, but I figured I might as well report it.

**Comment by oWave** [comment]
Fixed in v0.6
